/**
 * modules/admin_data_maintenance.js — Administration > Data Maintenance
 *
 * Reset an application's design data so it can be re-ingested from scratch,
 * while keeping the application's setup/config and (by default) its
 * Document Catalog entries so they can be resubmitted without re-uploading.
 * Backed by /api/v1/projects/:id/design-wipe-preview and /design-wipe, which
 * share the same table list as the backend-node/wipe-project.js CLI script.
 */
import { apiFetch, el, showToast } from '../app.js';

export async function render(container) {
  container.innerHTML = '';
  container.appendChild(el('div', { className: 'module-header' },
    el('h2', {}, 'Data Maintenance'),
    el('p', { className: 'purpose-text' },
      'Clears an application’s design data (use cases, workflows, requirements, and everything ' +
      'else generated by ingest) so it can be re-ingested from scratch. The application itself and its ' +
      'setup are always kept. By default, uploaded documents in the Document Catalog are also kept and ' +
      'reset so you can resubmit them without re-uploading — this is permanent and cannot be undone.')
  ));

  const panel = el('div', { className: 'panel' });
  panel.appendChild(el('div', { className: 'panel-header' }, el('h3', { className: 'panel-title' }, 'Reset an application')));
  const body = el('div', { className: 'panel-body', style: 'display:grid;gap:14px;max-width:720px' });

  const appSelect = el('select', { className: 'form-input' }, el('option', { value: '' }, 'Loading applications…'));
  body.appendChild(el('div', { className: 'form-group' }, el('label', { className: 'form-label' }, 'Application'), appSelect));

  const keepDocsCheckbox = el('input', { type: 'checkbox', id: 'keep-docs-checkbox' });
  keepDocsCheckbox.checked = true;
  const keepDocsRow = el('div', { style: 'display:flex;align-items:center;gap:8px' },
    keepDocsCheckbox,
    el('label', { for: 'keep-docs-checkbox' }, 'Keep Document Catalog entries (recommended — resets them so they can be resubmitted)')
  );
  body.appendChild(keepDocsRow);

  const previewBtn = el('button', { className: 'btn btn-secondary' }, 'Preview what will be deleted');
  const deleteBtn = el('button', { className: 'btn btn-danger', disabled: true }, 'Delete Design Data…');
  body.appendChild(el('div', { style: 'display:flex;gap:10px' }, previewBtn, deleteBtn));

  const resultBox = el('div', { style: 'margin-top:4px' });
  body.appendChild(resultBox);

  panel.appendChild(body);
  container.appendChild(panel);

  let projects = [];
  let lastPreview = null; // { projectId, keepDocuments, rows, total, project_name }

  function selectedProject() {
    return projects.find(p => p.project_id === appSelect.value) || null;
  }

  function invalidatePreview() {
    lastPreview = null;
    deleteBtn.disabled = true;
  }

  appSelect.addEventListener('change', invalidatePreview);
  keepDocsCheckbox.addEventListener('change', invalidatePreview);

  try {
    projects = await apiFetch('/projects');
    appSelect.innerHTML = '';
    if (!projects.length) {
      appSelect.appendChild(el('option', { value: '' }, 'No applications found'));
    } else {
      projects.forEach(p => {
        const label = `${p.client_name ? p.client_name + ' — ' : ''}${p.project_name}`;
        appSelect.appendChild(el('option', { value: p.project_id }, label));
      });
    }
  } catch (err) {
    appSelect.innerHTML = '';
    appSelect.appendChild(el('option', { value: '' }, 'Failed to load applications'));
    showToast('Failed to load applications: ' + err.message, 'error');
  }

  function renderPreview(preview) {
    resultBox.innerHTML = '';
    const { rows, total, keepDocuments, project_name } = preview;

    if (total === 0) {
      resultBox.appendChild(el('p', { className: 'dr-empty-note' }, `"${project_name}" has no design data — nothing to delete.`));
      return;
    }

    const table = el('table', { className: 'dr-compact-table', style: 'width:100%;margin-bottom:10px' });
    table.appendChild(el('thead', {}, el('tr', {}, el('th', {}, 'Table'), el('th', {}, 'Rows'))));
    const tbody = el('tbody');
    rows.forEach(r => tbody.appendChild(el('tr', {}, el('td', {}, r.label), el('td', {}, String(r.count)))));
    table.appendChild(tbody);
    resultBox.appendChild(table);
    resultBox.appendChild(el('p', { style: 'font-weight:600' }, `${total} rows will be deleted from "${project_name}."`));

    const docsRow = rows.find(r => r.label === 'asdlc_ingest_document');
    if (keepDocuments) {
      resultBox.appendChild(el('p', { style: 'color:var(--text-secondary);font-size:13px' },
        'Document Catalog entries will be kept and reset so they can be resubmitted for ingestion.'));
    } else if (docsRow) {
      resultBox.appendChild(el('p', { style: 'color:var(--danger);font-size:13px' },
        `Document Catalog entries will also be deleted (${docsRow.count} document${docsRow.count === 1 ? '' : 's'}).`));
    }
  }

  previewBtn.addEventListener('click', async () => {
    const project = selectedProject();
    if (!project) { showToast('Select an application first', 'error'); return; }
    previewBtn.disabled = true;
    try {
      const keepDocuments = keepDocsCheckbox.checked;
      const preview = await apiFetch(`/projects/${project.project_id}/design-wipe-preview?keepDocuments=${keepDocuments}`);
      lastPreview = { projectId: project.project_id, keepDocuments, ...preview };
      renderPreview(lastPreview);
      deleteBtn.disabled = lastPreview.total === 0;
    } catch (err) {
      showToast('Preview failed: ' + err.message, 'error');
      invalidatePreview();
    } finally {
      previewBtn.disabled = false;
    }
  });

  deleteBtn.addEventListener('click', () => {
    const project = selectedProject();
    if (!project || !lastPreview || lastPreview.projectId !== project.project_id || lastPreview.keepDocuments !== keepDocsCheckbox.checked) {
      showToast('Run a fresh preview for this application before deleting', 'error');
      return;
    }
    openConfirmModal(project, lastPreview, async () => {
      try {
        const res = await apiFetch(`/projects/${project.project_id}/design-wipe`, {
          method: 'POST',
          body: JSON.stringify({ keepDocuments: lastPreview.keepDocuments, confirmName: project.project_name }),
        });
        showToast(`Deleted ${res.total} rows from "${project.project_name}."`, 'success');
        if (!res.fkClean) showToast('Warning: integrity check found orphaned rows — notify an admin.', 'error');
        invalidatePreview();
        resultBox.innerHTML = '';
        resultBox.appendChild(el('p', { className: 'dr-empty-note' }, `Done — "${project.project_name}" is ready for fresh ingest.`));
      } catch (err) {
        showToast('Delete failed: ' + err.message, 'error');
      }
    });
  });
}

function openConfirmModal(project, preview, onConfirm) {
  const existing = document.getElementById('data-maintenance-confirm-modal');
  if (existing) existing.remove();

  const overlay = el('div', { id: 'data-maintenance-confirm-modal', className: 'modal-overlay' });
  const card = el('div', { className: 'modal-card', style: { width: '480px', maxWidth: '100%' } });

  card.appendChild(el('div', { className: 'modal-header' },
    el('h1', { style: { fontSize: '16px' } }, 'Confirm permanent deletion')
  ));

  const modalBody = el('div', { style: 'padding:16px 28px' },
    el('p', {}, `This will permanently delete ${preview.total} rows of design data from "${project.project_name}." This cannot be undone.`),
    el('p', {}, preview.keepDocuments
      ? 'Document Catalog entries will be kept and reset for re-ingestion.'
      : 'Document Catalog entries will also be deleted.'),
    el('p', { style: 'margin-top:12px' }, `Type the application name to confirm: `, el('strong', {}, project.project_name))
  );
  const confirmInput = el('input', { type: 'text', className: 'form-input', placeholder: project.project_name });
  modalBody.appendChild(confirmInput);
  card.appendChild(modalBody);

  const footer = el('div', { className: 'modal-footer' });
  const cancelBtn = el('button', { className: 'btn' }, 'Cancel');
  const confirmBtn = el('button', { className: 'btn btn-danger', disabled: true }, 'Delete permanently');
  cancelBtn.addEventListener('click', () => overlay.remove());
  confirmInput.addEventListener('input', () => {
    confirmBtn.disabled = confirmInput.value.trim() !== project.project_name;
  });
  confirmBtn.addEventListener('click', async () => {
    confirmBtn.disabled = true;
    cancelBtn.disabled = true;
    await onConfirm();
    overlay.remove();
  });
  footer.appendChild(cancelBtn);
  footer.appendChild(confirmBtn);
  card.appendChild(footer);

  overlay.appendChild(card);
  overlay.addEventListener('click', e => { if (e.target === overlay) overlay.remove(); });
  document.body.appendChild(overlay);
  confirmInput.focus();
}
